export const paises = [
    // {
    //     "id":"ESTADOS UNIDOS",
    //     "nombre":"ESTADOS UNIDOS"
    // },
    // {
    //     "id":"BÉLGICA",
    //     "nombre":"BÉLGICA"
    // },
    // {
    //     "id":"INGLATERRA",
    //     "nombre":"INGLATERRA"
    // },
    // {
    //     "id":"CHINA",
    //     "nombre":"CHINA"
    // },
    // {
    //     "id":"ESPAÑA",
    //     "nombre":"ESPAÑA"
    // },
    // {
    //     "id":"FRANCIA",
    //     "nombre":"FRANCIA"
    // },
    // {
    //     "id":"NORUEGA",
    //     "nombre":"NORUEGA"
    // },
    // {
    //     "id":"ECUADOR",
    //     "nombre":"ECUADOR"
    // },
    {
        "id": "N/A",
        "nombre": "N/A"
    },
    { "id": "AFGANISTÁN", "nombre": "AFGANISTÁN" },
    { "id": "ALBANIA", "nombre": "ALBANIA" },
    { "id": "ALEMANIA", "nombre": "ALEMANIA" },
    { "id": "ANDORRA", "nombre": "ANDORRA" },
    { "id": "ANGOLA", "nombre": "ANGOLA" },
    { "id": "ANGUILLA", "nombre": "ANGUILLA" },
    { "id": "ANTIGUA Y BARBUDA", "nombre": "ANTIGUA Y BARBUDA" },
    { "id": "ANTILLAS HOLANDESAS", "nombre": "ANTILLAS HOLANDESAS" },
    { "id": "ANTÁRTIDA", "nombre": "ANTÁRTIDA" },
    { "id": "ARABIA SAUDITA", "nombre": "ARABIA SAUDITA" },
    { "id": "ARGELIA", "nombre": "ARGELIA" },
    { "id": "ARGENTINA", "nombre": "ARGENTINA" },
    { "id": "ARMENIA", "nombre": "ARMENIA" },
    { "id": "ARUBA", "nombre": "ARUBA" },
    { "id": "AUSTRALIA", "nombre": "AUSTRALIA" },
    { "id": "AUSTRIA", "nombre": "AUSTRIA" },
    { "id": "AZERBAIYÁN", "nombre": "AZERBAIYÁN" },
    { "id": "BAHAMAS", "nombre": "BAHAMAS" },
    { "id": "BANGLADES", "nombre": "BANGLADES" },
    { "id": "BARBADOS", "nombre": "BARBADOS" },
    { "id": "BARÉIN", "nombre": "BARÉIN" },
    { "id": "BELICE", "nombre": "BELICE" },
    { "id": "BENIN", "nombre": "BENIN" },
    { "id": "BERMUDAS", "nombre": "BERMUDAS" },
    { "id": "BIELORRUSIA", "nombre": "BIELORRUSIA" },
    { "id": "BIRMANIA", "nombre": "BIRMANIA" },
    { "id": "BOLIVIA", "nombre": "BOLIVIA" },
    { "id": "BOSNIA-HERZEGOVINA", "nombre": "BOSNIA-HERZEGOVINA" },
    { "id": "BOTSUANA", "nombre": "BOTSUANA" },
    { "id": "BRASIL", "nombre": "BRASIL" },
    { "id": "BRUNEI", "nombre": "BRUNEI" },
    { "id": "BULGARIA", "nombre": "BULGARIA" },
    { "id": "BURKINA FASO", "nombre": "BURKINA FASO" },
    { "id": "BURUNDI", "nombre": "BURUNDI" },
    { "id": "BUTAN", "nombre": "BUTAN" },
    { "id": "BÉLGICA", "nombre": "BÉLGICA" },
    { "id": "CABO VERDE", "nombre": "CABO VERDE" },
    { "id": "CAMBOYA", "nombre": "CAMBOYA" },
    { "id": "CAMERÚN", "nombre": "CAMERÚN" },
    { "id": "CANADÁ", "nombre": "CANADÁ" },
    { "id": "CHAD", "nombre": "CHAD" },
    { "id": "CHEQUIA", "nombre": "CHEQUIA" },
    { "id": "CHILE", "nombre": "CHILE" },
    { "id": "CHINA", "nombre": "CHINA" },
    { "id": "CHIPRE", "nombre": "CHIPRE" },
    { "id": "CIUDAD DEL VATICANO", "nombre": "CIUDAD DEL VATICANO" },
    { "id": "COLOMBIA", "nombre": "COLOMBIA" },
    { "id": "COMORAS", "nombre": "COMORAS" },
    { "id": "CONGO", "nombre": "CONGO" },
    { "id": "COREA DEL NORTE", "nombre": "COREA DEL NORTE" },
    { "id": "COREA DEL SUR", "nombre": "COREA DEL SUR" },
    { "id": "COSTA DE MARFIL", "nombre": "COSTA DE MARFIL" },
    { "id": "COSTA RICA", "nombre": "COSTA RICA" },
    { "id": "CROACIA", "nombre": "CROACIA" },
    { "id": "CUBA", "nombre": "CUBA" },
    { "id": "DINAMARCA", "nombre": "DINAMARCA" },
    { "id": "DOMINICA", "nombre": "DOMINICA" },
    { "id": "ECUADOR", "nombre": "ECUADOR" },
    { "id": "EGIPTO", "nombre": "EGIPTO" },
    { "id": "EL SALVADOR", "nombre": "EL SALVADOR" },
    { "id": "EMIRATOS ÁRABES UNIDOS", "nombre": "EMIRATOS ÁRABES UNIDOS" },
    { "id": "ERITREA", "nombre": "ERITREA" },
    { "id": "ESLOVAQUIA", "nombre": "ESLOVAQUIA" },
    { "id": "ESLOVENIA", "nombre": "ESLOVENIA" },
    { "id": "ESPAñA", "nombre": "ESPAñA" },
    { "id": "ESTADO DE PALESTINA", "nombre": "ESTADO DE PALESTINA" },
    { "id": "ESTADOS FEDERADOS DE MICRONESIA", "nombre": "ESTADOS FEDERADOS DE MICRONESIA" },
    { "id": "ESTADOS UNIDOS", "nombre": "ESTADOS UNIDOS" },
    { "id": "ESTONIA", "nombre": "ESTONIA" },
    { "id": "ETIOPÍA", "nombre": "ETIOPÍA" },
    { "id": "FILIPINAS", "nombre": "FILIPINAS" },
    { "id": "FINLANDIA", "nombre": "FINLANDIA" },
    { "id": "FIYI", "nombre": "FIYI" },
    { "id": "FRANCIA", "nombre": "FRANCIA" },
    { "id": "GABÓN", "nombre": "GABÓN" },
    { "id": "GAMBIA", "nombre": "GAMBIA" },
    { "id": "GEORGIA", "nombre": "GEORGIA" },
    { "id": "GHANA", "nombre": "GHANA" },
    { "id": "GIBRALTAR", "nombre": "GIBRALTAR" },
    { "id": "GRANADA", "nombre": "GRANADA" },
    { "id": "GRECIA", "nombre": "GRECIA" },
    { "id": "GROENLANDIA", "nombre": "GROENLANDIA" },
    { "id": "GUADALUPE", "nombre": "GUADALUPE" },
    { "id": "GUAM", "nombre": "GUAM" },
    { "id": "GUATEMALA", "nombre": "GUATEMALA" },
    { "id": "GUAYANA FRANCESA", "nombre": "GUAYANA FRANCESA" },
    { "id": "GUERNSEY", "nombre": "GUERNSEY" },
    { "id": "GUINEA", "nombre": "GUINEA" },
    { "id": "GUINEA ECUATORIAL", "nombre": "GUINEA ECUATORIAL" },
    { "id": "GUINEA-BISAU", "nombre": "GUINEA-BISAU" },
    { "id": "GUYANA", "nombre": "GUYANA" },
    { "id": "HAITÍ", "nombre": "HAITÍ" },
    { "id": "HOLANDA", "nombre": "HOLANDA" },
    { "id": "HONDURAS", "nombre": "HONDURAS" },
    { "id": "HONG KONG", "nombre": "HONG KONG" },
    { "id": "HUNGRÍA", "nombre": "HUNGRÍA" },
    { "id": "INDIA", "nombre": "INDIA" },
    { "id": "INDONESIA", "nombre": "INDONESIA" },
    {
        "id": "INGLATERRA",
        "nombre": "INGLATERRA"
    },
    { "id": "IRAQ", "nombre": "IRAQ" },
    { "id": "IRLANDA", "nombre": "IRLANDA" },
    { "id": "IRÁN", "nombre": "IRÁN" },
    { "id": "ISLA DE MAN", "nombre": "ISLA DE MAN" },
    { "id": "ISLA DE NAVIDAD", "nombre": "ISLA DE NAVIDAD" },
    { "id": "ISLA DE SAN MARTÍN", "nombre": "ISLA DE SAN MARTÍN" },
    { "id": "ISLANDIA", "nombre": "ISLANDIA" },
    { "id": "ISLANORFOLK", "nombre": "ISLANORFOLK" },
    { "id": "ISLAS CAIMÁN", "nombre": "ISLAS CAIMÁN" },
    { "id": "ISLAS COCOS", "nombre": "ISLAS COCOS" },
    { "id": "ISLAS COOK", "nombre": "ISLAS COOK" },
    { "id": "ISLAS FEROE", "nombre": "ISLAS FEROE" },
    { "id": "ISLAS MALVINAS", "nombre": "ISLAS MALVINAS" },
    { "id": "ISLAS MARSHALL", "nombre": "ISLAS MARSHALL" },
    { "id": "ISLAS PITCAIRN", "nombre": "ISLAS PITCAIRN" },
    { "id": "ISLAS SALOMÓN", "nombre": "ISLAS SALOMÓN" },
    { "id": "ISLAS TURCAS Y CAICOS", "nombre": "ISLAS TURCAS Y CAICOS" },
    { "id": "ISLAS VÍRGENES BRITÁNICAS", "nombre": "ISLAS VÍRGENES BRITÁNICAS" },
    { "id": "ISLAS VÍRGENES DE LOS ESTADOS UNIDOS", "nombre": "ISLAS VÍRGENES DE LOS ESTADOS UNIDOS" },
    { "id": "ISLASMARIANASDELNORTE", "nombre": "ISLASMARIANASDELNORTE" },
    { "id": "ISRAEL", "nombre": "ISRAEL" },
    { "id": "ITALIA", "nombre": "ITALIA" },
    { "id": "JAMAICA", "nombre": "JAMAICA" },
    { "id": "JAPÓN", "nombre": "JAPÓN" },
    { "id": "JERSEY", "nombre": "JERSEY" },
    { "id": "JORDANIA", "nombre": "JORDANIA" },
    { "id": "KAZAJISTÁN", "nombre": "KAZAJISTÁN" },
    { "id": "KENIA", "nombre": "KENIA" },
    { "id": "KIRGUISTÁN", "nombre": "KIRGUISTÁN" },
    { "id": "KIRIBATI", "nombre": "KIRIBATI" },
    { "id": "KOSOVO", "nombre": "KOSOVO" },
    { "id": "KUWAIT", "nombre": "KUWAIT" },
    { "id": "LAOS", "nombre": "LAOS" },
    { "id": "LESOTO", "nombre": "LESOTO" },
    { "id": "LETONIA", "nombre": "LETONIA" },
    { "id": "LIBERIA", "nombre": "LIBERIA" },
    { "id": "LIBIA", "nombre": "LIBIA" },
    { "id": "LIECHTENSTEIN", "nombre": "LIECHTENSTEIN" },
    { "id": "LITUANIA", "nombre": "LITUANIA" },
    { "id": "LUXEMBURGO", "nombre": "LUXEMBURGO" },
    { "id": "LÍBANO", "nombre": "LÍBANO" },
    { "id": "MACAO", "nombre": "MACAO" },
    { "id": "MADAGASCAR", "nombre": "MADAGASCAR" },
    { "id": "MALASIA", "nombre": "MALASIA" },
    { "id": "MALAUI", "nombre": "MALAUI" },
    { "id": "MALDIVAS", "nombre": "MALDIVAS" },
    { "id": "MALTA", "nombre": "MALTA" },
    { "id": "MALÍ", "nombre": "MALÍ" },
    { "id": "MARRUECOS", "nombre": "MARRUECOS" },
    { "id": "MARTINICA", "nombre": "MARTINICA" },
    { "id": "MAURICIO", "nombre": "MAURICIO" },
    { "id": "MAURITANIA", "nombre": "MAURITANIA" },
    { "id": "MAYOTTE", "nombre": "MAYOTTE" },
    { "id": "MOLDAVIA", "nombre": "MOLDAVIA" },
    { "id": "MONACO", "nombre": "MONACO" },
    { "id": "MONGOLIA", "nombre": "MONGOLIA" },
    { "id": "MONTENEGRO", "nombre": "MONTENEGRO" },
    { "id": "MONTSERRAT", "nombre": "MONTSERRAT" },
    { "id": "MOZAMBIQUE", "nombre": "MOZAMBIQUE" },
    { "id": "MÉXICO", "nombre": "MÉXICO" },
    { "id": "NAMIBIA", "nombre": "NAMIBIA" },
    { "id": "NAURU", "nombre": "NAURU" },
    { "id": "NEPAL", "nombre": "NEPAL" },
    { "id": "NICARAGUA", "nombre": "NICARAGUA" },
    { "id": "NIGER", "nombre": "NIGER" },
    { "id": "NIGERIA", "nombre": "NIGERIA" },
    { "id": "NIUE", "nombre": "NIUE" },
    { "id": "NORUEGA", "nombre": "NORUEGA" },
    { "id": "NUEVA CALEDONIA", "nombre": "NUEVA CALEDONIA" },
    { "id": "NUEVA ZELANDA", "nombre": "NUEVA ZELANDA" },
    { "id": "OMÁN", "nombre": "OMÁN" },
    { "id": "PAKISTÁN", "nombre": "PAKISTÁN" },
    { "id": "PALAOS", "nombre": "PALAOS" },
    { "id": "PANAMÁ", "nombre": "PANAMÁ" },
    { "id": "PAPÚA NUEVA GUINEA", "nombre": "PAPÚA NUEVA GUINEA" },
    { "id": "PARAGUAY", "nombre": "PARAGUAY" },
    { "id": "PERÚ", "nombre": "PERÚ" },
    { "id": "POLINESIA FRANCESA", "nombre": "POLINESIA FRANCESA" },
    { "id": "POLONIA", "nombre": "POLONIA" },
    { "id": "PORTUGAL", "nombre": "PORTUGAL" },
    { "id": "PUERTO RICO", "nombre": "PUERTO RICO" },
    { "id": "QATAR", "nombre": "QATAR" },
    { "id": "REINO UNIDO", "nombre": "REINO UNIDO" },
    { "id": "REPÚBLICA CENTROAFRICANA", "nombre": "REPÚBLICA CENTROAFRICANA" },
    { "id": "REPÚBLICA DE MACEDONIA", "nombre": "REPÚBLICA DE MACEDONIA" },
    { "id": "REPÚBLICA DEMOCRÁTICA DEL CONGO", "nombre": "REPÚBLICA DEMOCRÁTICA DEL CONGO" },
    { "id": "REPÚBLICA DOMINICANA", "nombre": "REPÚBLICA DOMINICANA" },
    { "id": "REUNION", "nombre": "REUNION" },
    { "id": "RUANDA", "nombre": "RUANDA" },
    { "id": "RUMANIA", "nombre": "RUMANIA" },
    { "id": "RUSIA", "nombre": "RUSIA" },
    { "id": "SAMOA", "nombre": "SAMOA" },
    { "id": "SAMOA AMERICANA", "nombre": "SAMOA AMERICANA" },
    { "id": "SAN BARTOLOME", "nombre": "SAN BARTOLOME" },
    { "id": "SAN CRISTÓBAL Y NIEVES", "nombre": "SAN CRISTÓBAL Y NIEVES" },
    { "id": "SAN MARINO", "nombre": "SAN MARINO" },
    { "id": "SAN PEDRO Y MIQUELON", "nombre": "SAN PEDRO Y MIQUELON" },
    { "id": "SAN VICENTE Y LAS GRANADINAS", "nombre": "SAN VICENTE Y LAS GRANADINAS" },
    { "id": "SANTA ELENA, ASCENSIÓN Y TRISTÁN DE ACUñA", "nombre": "SANTA ELENA, ASCENSIÓN Y TRISTÁN DE ACUñA" },
    { "id": "SANTA LUCÍA", "nombre": "SANTA LUCÍA" },
    { "id": "SANTO TOMÉ Y PRÍNCIPE", "nombre": " SANTO TOMÉ Y PRÍNCIPE" },
    { "id": "SENEGAL", "nombre": "SENEGAL" },
    { "id": "SERBIA", "nombre": "SERBIA" },
    { "id": "SEYCHELLES", "nombre": "SEYCHELLES" },
    { "id": "SIERRA LEONA", "nombre": "SIERRA LEONA" },
    { "id": "SINGAPUR", "nombre": "SINGAPUR" },
    { "id": "SIRIA", "nombre": "SIRIA" },
    { "id": "SOMALIA", "nombre": "SOMALIA" },
    { "id": "SRI LANKA", "nombre": "SRI LANKA" },
    { "id": "SUAZILANDIA", "nombre": "SUAZILANDIA" },
    { "id": "SUDÁFRICA", "nombre": "SUDÁFRICA" },
    { "id": "SUDÁN", "nombre": "SUDÁN" },
    { "id": "SUDÁN DEL SUR", "nombre": "SUDÁN DEL SUR" },
    { "id": "SUECIA", "nombre": "SUECIA" },
    { "id": "SUIZA", "nombre": "SUIZA" },
    { "id": "SURINAM", "nombre": "SURINAM" },
    { "id": "SVALBARD Y JAN MAYEN", "nombre": "SVALBARD Y JAN MAYEN" },
    { "id": "TAILANDIA", "nombre": "TAILANDIA" },
    { "id": "TAIWÁN", "nombre": "TAIWÁN" },
    { "id": "TANZANIA", "nombre": "TANZANIA" },
    { "id": "TAYIKISTÁN", "nombre": "TAYIKISTÁN" },
    { "id": "TERRITORIO BRITÁNICO DEL OCÉANO ÍNDICO", "nombre": "TERRITORIO BRITÁNICO DEL OCÉANO ÍNDICO" },
    { "id": "TIMOR ORIENTAL", "nombre": "TIMOR ORIENTAL" },
    { "id": "TOGO", "nombre": "TOGO" },
    { "id": "TOKELAU", "nombre": "TOKELAU" },
    { "id": "TONGA", "nombre": "TONGA" },
    { "id": "TRINIDAD Y TOBAGO", "nombre": "TRINIDAD Y TOBAGO" },
    { "id": "TURKMENISTÁN", "nombre": "TURKMENISTÁN" },
    { "id": "TURQUÍA", "nombre": "TURQUÍA" },
    { "id": "TUVALU", "nombre": "TUVALU" },
    { "id": "TÚNEZ", "nombre": "TÚNEZ" },
    { "id": "UCRANIA", "nombre": "UCRANIA" },
    { "id": "UGANDA", "nombre": "UGANDA" },
    { "id": "URUGUAY", "nombre": "URUGUAY" },
    { "id": "UZBEKISTÁN", "nombre": "UZBEKISTÁN" },
    { "id": "VANUATU", "nombre": "VANUATU" },
    { "id": "VENEZUELA", "nombre": "VENEZUELA" },
    { "id": "VIETNAM", "nombre": "VIETNAM" },
    { "id": "WALLIS Y FUTUNA", "nombre": "WALLIS Y FUTUNA" },
    { "id": "YEMEN", "nombre": "YEMEN" },
    { "id": "YIBUTI", "nombre": "YIBUTI" },
    { "id": "ZAMBIA", "nombre": "ZAMBIA" },
    { "id": "ZIMBABUE", "nombre": "ZIMBABUE" },

]