export const paises= [
    {
        "id":"EEUU",
        "nombre":"EEUU"
    },
    {
        "id":"BÉLGICA",
        "nombre":"BÉLGICA"
    },
    {
        "id":"INGLATERRA",
        "nombre":"INGLATERRA"
    },
    {
        "id":"CHINA",
        "nombre":"CHINA"
    },
    {
        "id":"ESPAÑA",
        "nombre":"ESPAÑA"
    },
    {
        "id":"FRANCIA",
        "nombre":"FRANCIA"
    },
    {
        "id":"NORUEGA",
        "nombre":"NORUEGA"
    },
    {
        "id":"N/A",
        "nombre":"N/A"
    },
]